In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup # it is used for websccrapping

In [2]:
headers={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36'}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1',headers=headers).text

In [3]:
soup= BeautifulSoup(webpage,'lxml')

In [4]:
soup.find_all('h1')[0].text

'\n\t\t\t\t\tTop Companies in\n\t\t\t\t \n\t\t\t\t\tINDIA\n\t\t\t\t\t'

In [5]:
for i in soup.find_all('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
ICICI Bank
HCLTech
Tech Mahindra
Genpact
Teleperformance
Jio
Axis Bank
Concentrix Corporation
Amazon
iEnergizer
Reliance Retail
LTIMindtree
IBM
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [6]:
len(soup.find_all('div',class_ = 'rating_star_container'))

20

In [7]:
len(soup.find_all('a' , class_ = 'companyCardWrapper__ActionWrapper'))

120

In [10]:
com=soup.find_all('div',class_='companyCardWrapper')
print(len(com))

20

In [33]:
name=[]
rating = []
reviews=[]
description = []
for i in com:
    name.append(i.find('h2').text.strip())
    rating.append(i.find_all('div',class_='rating_star_container')[0].text.strip())
    reviews.append(i.find_all('a',class_='companyCardWrapper__ActionWrapper')[0].text.strip())
    description.append(i.find_all('span',class_='companyCardWrapper__interLinking')[0].text.strip())
name
rating
reviews
description

['IT Services & Consulting | Bangalore / Bengaluru +438 other locations',
 'IT Services & Consulting | Bangalore / Bengaluru +255 other locations',
 'IT Services & Consulting | Hyderabad / Secunderabad +370 other locations',
 'IT Services & Consulting | Hyderabad / Secunderabad +230 other locations',
 'IT Services & Consulting | Bangalore / Bengaluru +183 other locations',
 'Banking | Mumbai +1825 other locations',
 'IT Services & Consulting | Bangalore / Bengaluru +247 other locations',
 'Banking | Mumbai +1437 other locations',
 'IT Services & Consulting | Chennai +228 other locations',
 'IT Services & Consulting | Hyderabad / Secunderabad +332 other locations',
 'IT Services & Consulting | Hyderabad / Secunderabad +181 other locations',
 'BPO | Mumbai +255 other locations',
 'Telecom | Mumbai +1911 other locations',
 'Banking | Mumbai +1505 other locations',
 'BPO | Bangalore / Bengaluru +176 other locations',
 'Internet | Bangalore / Bengaluru +519 other locations',
 'BPO | Noida +51 other locations',
 'Retail | Mumbai +1156 other locations',
 'IT Services & Consulting | Bangalore / Bengaluru +145 other locations',
 'IT Services & Consulting | Bangalore / Bengaluru +160 other locations']

In [34]:
d={'NAME':name,'RATINGS':rating,'REVIEWS':reviews,'DESCRIPTION':description}
df=pd.DataFrame(d)
df

,NAME,RATINGS,REVIEWS,DESCRIPTION
0,TCS,3.3,1.1L Reviews,IT Services & Consulting | Bangalore / Bengalu...
1,Accenture,3.7,71.4k Reviews,IT Services & Consulting | Bangalore / Bengalu...
2,Wipro,3.6,63.5k Reviews,IT Services & Consulting | Hyderabad / Secunde...
3,Cognizant,3.6,59.8k Reviews,IT Services & Consulting | Hyderabad / Secunde...
4,Capgemini,3.7,51.4k Reviews,IT Services & Consulting | Bangalore / Bengalu...
5,HDFC Bank,3.8,50.7k Reviews,Banking | Mumbai +1825 other locations
6,Infosys,3.5,47.3k Reviews,IT Services & Consulting | Bangalore / Bengalu...
7,ICICI Bank,4.0,45.1k Reviews,Banking | Mumbai +1437 other locations
8,HCLTech,3.4,44.4k Reviews,IT Services & Consulting | Chennai +228 other ...
9,Tech Mahindra,3.4,42.4k Reviews,IT Services & Consulting | Hyderabad / Secunde...
10,Genpact,3.6,40.9k Reviews,IT Services & Consulting | Hyderabad / Secunde...
11,Teleperformance,3.8,36.6k Reviews,BPO | Mumbai +255 other locations
12,Jio,4.4,32.5k Reviews,Telecom | Mumbai +1911 other locations
13,Axis Bank,3.6,32.4k Reviews,Banking | Mumbai +1505 other locations
14,Concentrix Corporation,3.6,31.5k Reviews,BPO | Bangalore / Bengaluru +176 other locations
15,Amazon,3.9,30.7k Reviews,Internet | Bangalore / Bengaluru +519 other lo...
16,iEnergizer,4.6,27.1k Reviews,BPO | Noida +51 other locations
17,Reliance Retail,3.9,27k Reviews,Retail | Mumbai +1156 other locations
18,LTIMindtree,3.6,25.8k Reviews,IT Services & Consulting | Bangalore / Bengalu...
19,IBM,3.9,25.3k Reviews,IT Services & Consulting | Bangalore / Bengalu...

In [32]:
com[0].find_all('div',class_="companyCardWrapper__ratingComparisonWrapper")[0].text.strip()

'Highly Rated For Job Security  Critically Rated For Promotions / Appraisal, Salary & Benefits, Work Satisfaction'

In [45]:
final_ =[]
for j in range(1,3):
    url='https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page={}'.format(j)
    headers={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36'}
    webpage = requests.get(url,headers=headers).text
    soup= BeautifulSoup(webpage,'lxml')
    com=soup.find_all('div',class_='companyCardWrapper')
    
    name=[]
    rating = []
    reviews=[]
    description = []
    for i in com:
        name.append(i.find('h2').text.strip())
        rating.append(i.find_all('div',class_='rating_star_container')[0].text.strip())
        reviews.append(i.find_all('a',class_='companyCardWrapper__ActionWrapper')[0].text.strip())
        description.append(i.find_all('span',class_='companyCardWrapper__interLinking')[0].text.strip())
    d={'NAME':name,'RATINGS':rating,'REVIEWS':reviews,'DESCRIPTION':description}
    df=pd.DataFrame(d)
    final_.append(df)
final_list=pd.concat(final_,ignore_index=True)
final_list

,NAME,RATINGS,REVIEWS,DESCRIPTION
0,TCS,3.3,1.1L Reviews,IT Services & Consulting | Bangalore / Bengalu...
1,Accenture,3.7,71.4k Reviews,IT Services & Consulting | Bangalore / Bengalu...
2,Wipro,3.6,63.5k Reviews,IT Services & Consulting | Hyderabad / Secunde...
3,Cognizant,3.6,59.8k Reviews,IT Services & Consulting | Hyderabad / Secunde...
4,Capgemini,3.7,51.4k Reviews,IT Services & Consulting | Bangalore / Bengalu...
5,HDFC Bank,3.8,50.7k Reviews,Banking | Mumbai +1825 other locations
6,Infosys,3.5,47.3k Reviews,IT Services & Consulting | Bangalore / Bengalu...
7,ICICI Bank,4.0,45.1k Reviews,Banking | Mumbai +1437 other locations
8,HCLTech,3.4,44.4k Reviews,IT Services & Consulting | Chennai +228 other ...
9,Tech Mahindra,3.4,42.4k Reviews,IT Services & Consulting | Hyderabad / Secunde...
10,Genpact,3.6,40.9k Reviews,IT Services & Consulting | Hyderabad / Secunde...
11,Teleperformance,3.8,36.6k Reviews,BPO | Mumbai +255 other locations
12,Jio,4.4,32.5k Reviews,Telecom | Mumbai +1911 other locations
13,Axis Bank,3.6,32.4k Reviews,Banking | Mumbai +1505 other locations
14,Concentrix Corporation,3.6,31.5k Reviews,BPO | Bangalore / Bengaluru +176 other locations
15,Amazon,3.9,30.7k Reviews,Internet | Bangalore / Bengaluru +519 other lo...
16,iEnergizer,4.6,27.1k Reviews,BPO | Noida +51 other locations
17,Reliance Retail,3.9,27k Reviews,Retail | Mumbai +1156 other locations
18,LTIMindtree,3.6,25.8k Reviews,IT Services & Consulting | Bangalore / Bengalu...
19,IBM,3.9,25.3k Reviews,IT Services & Consulting | Bangalore / Bengalu...
20,HDB Financial Services,3.9,25.2k Reviews,NBFC | Mumbai +1092 other locations
21,Larsen & Toubro Limited,3.9,23.3k Reviews,Engineering & Construction | Chennai +759 othe...
22,Deloitte,3.7,22.4k Reviews,Management Consulting | Hyderabad / Secunderab...
23,Kotak Mahindra Bank,3.6,21.9k Reviews,Banking | Mumbai +684 other locations
24,Reliance Industries,4.0,19.8k Reviews,Oil & Gas | Jamnagar +814 other locations
25,Vodafone Idea,3.9,17.5k Reviews,Telecom | Pune +702 other locations
26,Bharti Airtel,3.8,16.8k Reviews,Telecom | Gurgaon / Gurugram +790 other locations
27,BYJU'S,3.2,16.4k Reviews,EdTech | Bangalore / Bengaluru +322 other loca...
28,WNS,3.3,14.8k Reviews,IT Services & Consulting | Pune +65 other loca...
29,IDFC FIRST Bank,3.9,14k Reviews,Banking | Mumbai +714 other locations
30,Tata Motors,4.1,14k Reviews,Automobile | Pune +506 other locations
31,Ernst & Young,3.4,14k Reviews,Management Consulting | Bangalore / Bengaluru ...
32,IndusInd Bank,3.4,13.9k Reviews,Banking | Mumbai +789 other locations
33,AU Small Finance Bank,3.9,13.8k Reviews,Banking | Jaipur +786 other locations
34,Bajaj Finserv,3.9,12.6k Reviews,NBFC | Pune +1167 other locations
35,Flipkart,3.9,12.6k Reviews,Internet | Bangalore / Bengaluru +557 other lo...
36,Muthoot FinCorp,4.5,12.3k Reviews,NBFC | Bangalore / Bengaluru +1098 other locat...
37,PwC,3.3,12.1k Reviews,Management Consulting | Bangalore / Bengaluru ...
38,Mahindra & Mahindra,4.0,11.8k Reviews,Automobile | Pune +561 other locations
39,DXC Technology,3.6,11.8k Reviews,IT Services & Consulting | Bangalore / Bengalu...